### ISSUE TITLE
Disables VSCodes built in Emmet extension on Mac OS 

### ISSUE THREAD

**Issue by ramseylove** [rbtsolis/django-vscode#1]
When I Installed and enabled this extension, it immediately stopped VsCodes build in Emmet extension from working. When I disabled it this extension, Emmet worked again.

Running version 1.38.1 on Mac OS 10.14.6

**Comment by BarbaAlGhul** [comment]
I'm facing the same problem, running version 1.0.2 on a Manjaro Linux 18.1.0 "Juhraya"

EDIT:
Ok, found the solution, I had to add
`"emmet.includeLanguages": {
        "django-html": "html"
    }`
on settings.json

**Comment by rbtsolis** [comment]
:O Thanks for the feedback, I will try to find a solution for that

**Comment by wadlo2042** [comment]
@BarbaAlGhul I tried your fix but it seemed to break the django snippets. Syntax highlighting is still working fine but I can't use snippets like block for example. Did you do anything other than emmet mapping?

**Comment by rbtsolis** [comment]
@BarbaAlGhul added a solution for this, it works
